@echo off
title GnuCash Bills - Starting...
echo Starting GnuCash Bills server on port 7432...
start /min "GnuCash Bills Server" cmd /k "cd /d D:\Users\Conrad\Documents\programming\GnuCash_bills_and_collections && uv run uvicorn bill_processor.web.app:app --port 7432"
echo Waiting for server to start...
timeout /t 2 /nobreak >nul
echo Opening browser...
start http://localhost:7432
echo Done. Server is running in the background (minimized in taskbar).
echo Close the minimized console window to stop the server.
timeout /t 3 /nobreak >nul
